name: Build and Notify Central Repo

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Instalar dependencias y compilar el proyecto
      - name: Install and build
        run: |
          npm install
          npm run build

      # 3. Comprimir el proyecto (opcional)
      - name: Zip build folder
        run: zip -r build.zip ./dist

      # 4. Subir el proyecto como artefacto
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: vue-project-build
          path: build.zip

  notify-central-repo:
    runs-on: ubuntu-latest
    needs: build-and-upload

    steps:
      # 1. Obtener el ID del artefacto generado
      - name: Get Artifact ID
        id: get-artifact
        run: |
          ARTIFACT_ID=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/artifacts \
            | jq -r '.artifacts[0].id')
          echo "artifact-id=$ARTIFACT_ID" >> $GITHUB_ENV

      # 2. Notificar al repositorio central
      - name: Notify central repo
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.PROJECT_ACCESS_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/null-point-sys/front_testing/dispatches \
          -d '{"event_type":"new-artifact", "client_payload": {"artifact_id": "${{ env.artifact-id }}", "repo_owner": "wbsckt3", "repo_name": "techGuardRips"}}'
